---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
      - id: clang-format
        exclude: ".json"
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
      - id: cmakelint
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.0.1
      hooks:
      -   id: reorder-python-imports
          args: [--py310-plus]
  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      -   id: black
  -   repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
      -   id: flake8
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.942
      hooks:
      -   id: mypy
          additional_dependencies: [types-all,]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
  -   repo: https://github.com/sco1/brie-commit
      rev: v1.1.0
      hooks:
      -   id: brie-commit
